### ISSUE TITLE
无效的窗口句柄

### ISSUE THREAD

**Issue by Nomination-NRB** [HuYo-OS/Genshin_auto_fish#9]
(ysfish) C:\Users\76608\Genshin_auto_fish>**python fishing.py image -f yolox/exp/yolox_tiny_fish.py -c weights/best_tiny3.pth --conf 0.25 --nms 0.45 --tsize 640 --device cpu**
Traceback (most recent call last):
  File "fishing.py", line 19, in <module>
    from fisher.environment import *
  File "C:\Users\76608\Genshin_auto_fish\fisher\environment.py", line 5, in <module>
    from utils import *
  File "C:\Users\76608\Genshin_auto_fish\utils\__init__.py", line 2, in <module>
    from .utils import *
  File "C:\Users\76608\Genshin_auto_fish\utils\utils.py", line 30, in <module>
    gvars.genshin_window_rect = win32gui.GetWindowRect(hwnd)
pywintypes.error: **(1400, 'GetWindowRect', '无效的窗口句柄。')**

_**默认前面的操作都是正常的，但是在使用CPU模式下的指令时，报错：无效的窗口**_

**Comment by LittleMio** [comment]
要先开游戏再运行

**Comment by Nomination-NRB** [comment]
> 要先开游戏再运行

此问题已解决，感谢；目前可以运行，但是是一顿一顿的（不知道是不是CPU带不动，之后会尝试GPU的方法），抛竿和选点需要20s左右，鱼儿咬勾之后力度直接拉到最大了，这是因为没有训练的问题吗

**Comment by LittleMio** [comment]
CPU跑的话会非常卡，力度问题的话，请确认游戏分辨率是以1920X1080运行的（如果你已经以1920X1080分辨率运行了，那么可能和使用CPU运行有关）

从 Windows 版邮件发送

发件人: Kyobo
发送时间: 2022年5月3日 23:05
收件人: HuYo-OS/Genshin_auto_fish
抄送: HUYO-OS; Comment
主题: Re: [HuYo-OS/Genshin_auto_fish] 无效的窗口句柄 (Issue #9)

要先开游戏再运行
此问题已解决，感谢；目前可以运行，但是是一顿一顿的（不知道是不是CPU带不动，之后会尝试GPU的方法），抛竿和选点需要20s左右，鱼儿咬勾之后力度直接拉到最大了，这是因为没有训练的问题吗

**Comment by Nomination-NRB** [comment]
> CPU跑的话会非常卡，力度问题的话，请确认游戏分辨率是以1920X1080运行的（如果你已经以1920X1080分辨率运行了，那么可能和使用CPU运行有关） 从 Windows 版邮件发送 发件人: Kyobo 发送时间: 2022年5月3日 23:05 收件人: HuYo-OS/Genshin_auto_fish 抄送: HUYO-OS; Comment 主题: Re: [HuYo-OS/Genshin_auto_fish] 无效的窗口句柄 (Issue #9) 要先开游戏再运行 此问题已解决，感谢；目前可以运行，但是是一顿一顿的（不知道是不是CPU带不动，之后会尝试GPU的方法），抛竿和选点需要20s左右，鱼儿咬勾之后力度直接拉到最大了，这是因为没有训练的问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的好的，我明白了（十分感谢你！）

**Comment by LittleMio** [comment]
不用谢，哈哈

从 Windows 版邮件发送

发件人: Kyobo
发送时间: 2022年5月3日 23:10
收件人: HuYo-OS/Genshin_auto_fish
抄送: HUYO-OS; Comment
主题: Re: [HuYo-OS/Genshin_auto_fish] 无效的窗口句柄 (Issue #9)

CPU跑的话会非常卡，力度问题的话，请确认游戏分辨率是以1920X1080运行的（如果你已经以1920X1080分辨率运行了，那么可能和使用CPU运行有关） 从 Windows 版邮件发送 发件人: Kyobo 发送时间: 2022年5月3日 23:05 收件人: HuYo-OS/Genshin_auto_fish 抄送: HUYO-OS; Comment 主题: Re: [HuYo-OS/Genshin_auto_fish] 无效的窗口句柄 (Issue #9) 要先开游戏再运行 此问题已解决，感谢；目前可以运行，但是是一顿一顿的（不知道是不是CPU带不动，之后会尝试GPU的方法），抛竿和选点需要20s左右，鱼儿咬勾之后力度直接拉到最大了，这是因为没有训练的问题吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>
好的好的，我明白了（十分感谢你！）
